### ISSUE TITLE
Stream packets to S3 buckets

### ISSUE THREAD

**Issue by sandman137** [deepfence/PacketStreamer#2]
Essentially 
sensor -> receiver -> S3

**Comment by r8ygun** [comment]
@sandman137 Do you have any preference on how the bucket keys are named/configured for this feature? For example, would there be one object in the bucket and users provide both the bucket name and the key in their config, or would the config only take the bucket name and the key becomes something like the date in yyyy-mm-dd format?

**Comment by sandman137** [comment]
@r8ygun Open for suggestions but we have been thinking about adhering to fluent-bit style for output plugins. In case of S3, adding region makes total sense due to costs involved.

https://docs.fluentbit.io/manual/pipeline/outputs/s3/

@vadorovsky do you agree?

**Comment by vadorovsky** [comment]
Yes, I agree with using fluentbit style of s3 output config and using AWS "parts" for uploading.

@r8ygun My idea for the key name is using something like `/packetstreamer/%Y/%m/%d/%H/%M/%S` and letting users to configure it as a date-formatted string. Does that work for you?

**Comment by vadorovsky** [comment]
> Yes, I agree with using fluentbit style of s3 output config and using AWS "parts" for uploading.

Hmm... on the other hand, it's hard to predict how big the final outputs of PacketStreamer are going to be. And I think it will be the best to upload the pcap output as often as possible - now I'm thinking about doing that in 1MB or 5MB (of course that would be configurable) separate files, using the `PubObject` S3 API, to not wait too long in between uploads.

**Comment by r8ygun** [comment]
@vadorovsky I've started work on this on my fork taking the approach of using Multipart uploads primarily. Given that Packetstreamer already goes to the length of re-using buffers etc, it seems a bit wasteful _not_ to utilise that in some way.  My idea is that we accept the Fluent style config as you've both described above, and  do the following:

- Accept totalFileSize and uploadChunkSize from config, but if the latter is < 5MB, set it as 5MB.  Each _part_ in a multipart upload needs to be >= 5MB IIRC.
- Accept uploadTimeout from config.  If the amount of data received in the timeout internal is < 5MB, use a normal `PutObject` operation, otherwise carry on with a multipart. We could set the default of `uploadTimeout` to be quite small (30s?) if we wanted frequent file uploads as the normal behaviour.

If this was the behaviour, we'd only really keep roughly `uploadChunkSize` or less of data in memory before it gets flushed out one way or the other.

Maybe this is use-case dependant. Is it preferable to have lots of "smaller" files than

**Comment by r8ygun** [comment]
I've just spotted that you've also started working on this. I've raised a draft PR if you want to have a look - #11, otherwise I'll leave you to it :)

**Comment by vadorovsky** [comment]
It's done
