### ISSUE TITLE
Stream packets to Kafka

### ISSUE THREAD

**Issue by sandman137** [deepfence/PacketStreamer#3]
Essentially
sensor -> receiver -> Kafka

**Comment by r8ygun** [comment]
I've started working on this on my fork - happy if you want to assign it.

**Comment by sandman137** [comment]
Awesome, just assigned it to you @r8ygun

**Comment by r8ygun** [comment]
@sandman137 I've raised a draft PR (#20) with some questions/notes.  It's not code complete, but it would be good to get your/others input before I mark it as ready as there will be some stuff to do depending on what behaviour you all expect.

**Comment by sandman137** [comment]
@r8ygun thank you. I will let @vadorovsky comment on the same and take it to closure.

**Comment by vadorovsky** [comment]
Ryan's PR was merged, thanks for your contribution!

But I will keep this issue open. As you can see, the arm64 build fails:

https://github.com/deepfence/PacketStreamer/runs/6415308027?check_suite_focus=true

That's because https://github.com/confluentinc/confluent-kafka-go is wrapping a C library and providing vendored .a files built for x64... As a workaround for other architectures they suggest to build kafka manually.

That doesn't sound good for me and I would rather try some library written entirely in Go, like:

https://github.com/segmentio/kafka-go

I will try using it as soon as I have time for that.
