### ISSUE TITLE
Support output to stdout

### ISSUE THREAD

**Issue by ogarrett** [deepfence/PacketStreamer#5]
Output file is defined by the configuration `output: file: path: filename`

There are use cases where you might want to write to stdout, such as in stream processing where you don't want to maintain a large file on disk:

`./packet-streamer receiver --config contrib/receiver-stdout.yaml | tcpdump -r - | grep something`

You can set the filename to `/dev/stdout`, but this has limitations if the user has changed permissions ([example](https://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied)).

**Feature request:** allow a user to write to stdout.  For example, we could support a special filename '`-`' or '`stdout`', or a different configuration `output: file: stdout`

**Comment by vadorovsky** [comment]
We also log info messages to stdout, so I don't really think that we want to pipe them to tcpdump. And since the most of people with use PacketStreamer either in Kubernetes or as a systemd unit in production, I think that the main purpose of stdout should be Info log messages.

For your usecase, I think it's better to just `tail` the output file? That way you would ensure piping only the pcap info.

**Comment by ogarrett** [comment]
We should log operational and error messages to stderr, and provide the option to write pcap data to stdout.

This makes processing the packet data so much easier.  It avoids consuming lots of disk, and helps when restarting the packetstreamer receiver because you don't need to search forwards through the pcap log file to skip messages already seen.
